Add NGCC + SOEC Flowsheet
IDAES/examples-pse pull request #114
Opened 2022-05-06 01:56 UTC by eslickj

This add the NGCC + SOEC flowsheet and notebook.  The SOEC uses steam and power from the NGCC to generate hydrogen.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-05-06 14:20 UTC, andrewlee94 requested changes
I found a quite a few lines of commented code that should be checked and removed if not required.

I also found some typos in the notebook, but GitHub won't let me do line by line comments there (too big?).

 - [x] Introduction: off-design, number, estimated, size ("numebr of cells is etimated from a given cell sized")
 - [x] Import Required Modules: a number of deprecation warnings here - I think these are coming from the soec modules however and might already have been fixed (but the notebook not updated to account for this).
 - [x] Make Output Directories: ensures
 - [x] Set Global Solver Options: "allows it to uses provided" - "uses" is definitely wrong, but I am not sure if you mean "use" or "use user"
 - [x] Create and Initialize the NGCC + SOEC Model: Generated output is very long - you might want to consider changing the logger level to hide most of this.
 - [ ] There is not a lot of description of what is happening at each step after the initialization - a little more guidance for the reader would probably be helpful.
 - [x] After output cell 9: "Gas Trubine Section" - this looks like it might be a typo in the "display_pdf" code

2022-05-06 14:20 UTC, andrewlee94 commented on src/Examples/Flowsheets/ngcc/hrsg.py
> +            # self.g09,
Is there a reason why these lines are commented out? If there is a reason to keep them, a comment on why would be helpful.

2022-05-06 14:20 UTC, andrewlee94 commented on src/Examples/Flowsheets/ngcc/hrsg.py
> +        # res = solver_obj.solve(self, tee=True)
Commented line.

2022-05-06 14:20 UTC, andrewlee94 commented on src/Examples/Flowsheets/ngcc/ngcc_soec.py
> +        "This is a desing point only model."
Typo: design

2022-05-06 14:20 UTC, andrewlee94 commented on src/Examples/Flowsheets/ngcc/soec_flowsheet_costing.py
> +    m.get_costing(year="2018")
This is probably a topic for a separate issue and PR, but this appears to be using the old-style costing approach which is going to be removed in November.

2022-05-06 14:20 UTC, andrewlee94 commented on src/Examples/Flowsheets/ngcc/soec.py
> +        # self.soec = SoecDesign(
Commented code.

2022-05-06 14:20 UTC, andrewlee94 commented on src/Examples/Flowsheets/ngcc/soec.py
> +        # self.assumed_cell_area = pyo.Var(initialize=0.0550, units=pyo.units.m**2)
Commented code

2022-05-06 14:20 UTC, andrewlee94 commented on src/Examples/Flowsheets/ngcc/soec.py
> +        # for pp in [self.h2_side_prop_params,self.o2_side_prop_params]:
Commented code

2022-05-06 14:20 UTC, andrewlee94 commented on src/Examples/Flowsheets/ngcc/soec.py
> +        # self.soec.fuel_outlet.temperature.fix(1023)
Commented lines

2022-05-06 14:20 UTC, andrewlee94 commented on src/Examples/Flowsheets/ngcc/soec.py
> +        # self.soec.oxygen_side_inlet.mole_frac_comp[:, "H2"].fix(0.23)
Commented lines

2022-05-06 14:20 UTC, andrewlee94 commented on src/Examples/Flowsheets/ngcc/soec.py
> +        # self.feed_recycle_mix.feed.pressure.unfix()
Commented line

2022-05-12 21:55 UTC, eslickj commented on src/Examples/Flowsheets/ngcc/soec.py
> +        # Magic dryer, just magically drop water out of a port.
I'll look at flashes and dry after this PR.

2022-05-12 22:05 UTC, eslickj commented
@dallan-keylogic and @andrewlee94 this should be all fixed up.  @AlexNoring, I may need you to take a look if Andrew is not available.

2022-05-13 13:03 UTC, andrewlee94 reviewed
My only significant comment here is that I don't see any changes to the files required to link these up to the indexing of the examples in the docs and thus testing of the examples. I think we need to have these things to make these useful (and findable) to the user.

2022-05-13 14:49 UTC, dallan-keylogic requested changes

2022-05-13 14:49 UTC, dallan-keylogic commented on src/Examples/Flowsheets/ngcc/soec.py
> +        self.soec_stack.solid_oxide_cell.recursive_scaling()
The module-level `calculate_scaling_factors` method calls the cell-level `recursive_scaling` after pulling scaling factors from the property packages, so we shouldn't call this method directly when using the module model.

2022-05-13 14:49 UTC, dallan-keylogic commented on src/Examples/Flowsheets/ngcc/soec.py
> +        self.soec_stack.solid_oxide_cell.potential.unfix()
Should be fixing and unfixing the stack-level reference variable `potential_cell`

2022-05-13 14:49 UTC, dallan-keylogic commented on src/Examples/Flowsheets/ngcc/soec.py
> +        self.soec_stack.solid_oxide_cell.fuel_inlet.unfix()
Similarly, fix and unfix the stack-level inlet ports, not the cell level ones.

2022-05-13 14:49 UTC, dallan-keylogic commented on src/Examples/Flowsheets/ngcc/soec.py
> +            expr=self.soec_stack.solid_oxide_cell.potential[0],
Reference `soec_stack.potential_cell`

2022-05-13 14:49 UTC, dallan-keylogic commented on src/Examples/Flowsheets/ngcc/soec_flowsheet_costing.py
> +        return c.total_plant_cost * 1e6 == 60.87 * m.soec_stack.number_cells
Probably move this costing constraint to the module block.

2022-05-13 14:49 UTC, dallan-keylogic commented on src/Examples/Flowsheets/ngcc/soec.py
> +        self.soec_stack = soc.SolidOxideModuleSimple(
To be really pedantic, we should probably use `soec_module` instead of `soec_stack`, because one module can contain many stacks.

2022-05-13 15:57 UTC, eslickj commented
> My only significant comment here is that I don't see any changes to the files required to link these up to the indexing of the examples in the docs and thus testing of the examples. I think we need to have these things to make these useful (and findable) to the user.

@andrewlee94, I think they are already linked because there is already a link for the ngcc folder.

2022-05-13 16:05 UTC, andrewlee94 submitted a review, later dismissed
OK, it looks like these are getting picked up in the tests at least.

2022-05-14 15:27 UTC, eslickj commented on src/Examples/Flowsheets/ngcc/soec.py
> +                / b.soec_stack.solid_oxide_cell.fuel_channel.flow_mol_comp_inlet[t, "H2O"]
I don't think flow_mol_comp is a port variable, so I'l have to do a little more calculation.

2022-05-14 16:00 UTC, eslickj commented on src/Examples/Flowsheets/ngcc/ngcc_soec.ipynb
> +    "make_decision_var(m.fs.soec.soec_stack.solid_oxide_cell.potential[0], 1.28, 1.38)\n",
I don't know,  it just never goes that low so I never had reason to lower it.

2022-05-14 16:42 UTC, eslickj commented on src/Examples/Flowsheets/ngcc/ngcc.ipynb
>      "use_idaes_solver_configuration_defaults()\n",
I don't thinks so.  I looked at where the notebooks are run in the tests, and I'm fairly sure they are run in a subprocess, so I think they are all independent.

2022-05-14 16:57 UTC, eslickj commented on src/Examples/Flowsheets/ngcc/ngcc_soec.ipynb
>     ],
I'm adding a comment but unless I'm missing something I don't think the constraints are redundant.  The "h" and "o" constraints are for one side so like h side going from 100 to 140 along with o side going from 300 to 340 is okay.  The 1 and two constraints make sure the two sides temperature are not more than 40 degrees apart at the ports.

2022-05-16 18:46 UTC, dallan-keylogic approved these changes

2022-05-16 19:07 UTC, merged