Update NGCC SOEC example for new costing methods
IDAES/examples-pse pull request #151
Opened 2022-10-04 20:18 UTC by bpaul4

## Fixes # .

## Proposed changes:
- Re-runs notebook to remove warnings currently visible in GitHub version of example
- Updates costing to use new power plant costing methods
- Note: this will work once # is merged, and this PR should be merged ASAP afterwards since the new methods will break the existing notebook

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-10-04 20:44 UTC, bpaul4 commented
Until the new power plant costing methods are merged, the expected outcome is that only the NGCC SOEC example fails (due to an `ImportError`).

2022-10-14 13:39 UTC, lbianchi-lbl requested changes
Nothing against the changes in the PR, this is simply a reminder to restore the `idaes-pse` pull URL before merging this PR (hopefully pushing that change should automatically dismiss this review; otherwise, feel free to ping me).

2022-10-14 13:39 UTC, lbianchi-lbl commented on .github/workflows/main.yml
> +  IDAES_PSE_REQUIREMENT: idaes-pse[prerelease] @ git+https://github.com/IDAES/idaes-pse@refs/pull/978/head
Just a reminder to switch this back to the original line before merging this PR.

2022-10-14 16:03 UTC, lbianchi-lbl approved these changes

2022-10-27 19:17 UTC, AlexNoring approved these changes
lgtm

2022-10-27 19:24 UTC, merged