1D fixed bed adsorption/desorption example
IDAES/examples-pse pull request #152
Opened 2022-10-12 18:46 UTC by chineduobiora

## Fixes # .

## Proposed changes:
- Temperature swing adsorption of CO2 example with the IDAES 1D fixed bed model

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-10-12 18:51 UTC, chineduobiora commented
Note that for this notebook a local copy of the 1DFixedBed model is currently used. It will be removed and replaced with the model from the idaes-pse libraries when the PR (https://github.com/IDAES/idaes-pse/pull/984) is approved.

2022-12-01 21:45 UTC, aostace01 reviewed
This looks good so far (still have some files to go over). Some comments related to two .svg files – these should not hold up the PR’s approval, but it would be nice to have them addressed if not too laborious:
•	plant_pfd.svg: Noticed some slight inconsistency: some unit operations and streams are capitalized (e.g., Downcomer, HP/IP/LP Turbine), while others aren't (e.g., air preheater, condensate pump).
•	boiler_scpc_PFD.svg: The legend has "FM" denoting the mass flow (kg/s), however on the flowsheet the mass flow seems to be denoted by "Fm". Also, "moisture" and "HHV" are not in the legend. Lastly, the green-colored streams are not listed in the legend (and some colors that don't show up on the flowsheet are listed).

2022-12-01 21:45 UTC, aostace01 commented on notebook_index.yml
> +            title: Temperature Swing Adsorption Using 1D Fixed Bed Model
Should the title be in quotation marks?  (`title: "Temperature Swing Adsorption Using 1D Fixed Bed Model"`)

2022-12-01 22:52 UTC, aostace01 reviewed
Some typos that stood out in `temperature_swing_adsorption/TSA_CO2_example_1DFixedBed.ipynb`:

2022-12-01 22:52 UTC, aostace01 commented on src/Examples/Flowsheets/temperature_swing_adsorption/TSA_CO2_example_1DFixedBed.ipynb
> +    "- A. Lee, D.C. Miller, A One-Dimensional (1-D) Three-Region Model for a Bubbling Fluidized-Bed Adsorber, Ind. Eng. Chem. Res. 52 (2013) 469–484\n",
The original paper presenting the development of the kinetic and equilibrium model for the adsorption of CO2 onto the NETL 32D sorbent should also be cited here: 

Lee, A.; Mebane, D.; Fauth, D. J.; Miller, D. C. A Model for the Adsorption Kinetics of CO2 on Amine-Impregnated Mesoporous Sorbents in the Presence of Water. Presented at the 28th International Pittsburgh Coal Conference, Pittsburgh, PA, 2011.

2022-12-01 22:52 UTC, aostace01 commented on src/Examples/Flowsheets/temperature_swing_adsorption/TSA_CO2_example_1DFixedBed.ipynb
> +    "The notebook demonstrates how to use the IDAES 1DFixedBed model for a TSA application with distinct adsorption and desorption steps, and also shows how to simulate the adsorption and desorption
If I am not mistaken, Petsc is usually spelled as PETSc.

2022-12-01 22:52 UTC, aostace01 commented on src/Examples/Flowsheets/temperature_swing_adsorption/TSA_CO2_example_1DFixedBed.ipynb
> +    "- Initial condition (except temperature) of sorbent in desorption step is set to final condition of sorbent in adsorption step."
Some bullet points end in a period, others don't.

2022-12-01 22:52 UTC, aostace01 commented on src/Examples/Flowsheets/temperature_swing_adsorption/TSA_CO2_example_1DFixedBed.ipynb
> +    "- Isothermal conditions: heat duty requirements of each step are calculated from gas and sorbent properties i.e. loading, density, heat of adsorption, and heat capacity\n",
Comma missing around "i.e.".

2022-12-01 22:52 UTC, aostace01 commented on src/Examples/Flowsheets/temperature_swing_adsorption/TSA_CO2_example_1DFixedBed.ipynb
> +    "- value (to return the numerical value of an Pyomo objects such as variables, constraints or expressions)\n",
Typo: "an" should be removed from before "Pyomo objects".

2022-12-01 22:52 UTC, aostace01 commented on src/Examples/Flowsheets/temperature_swing_adsorption/TSA_CO2_example_1DFixedBed.ipynb
> +    "- petsc (petsc integrator)\n",
I think the second "petsc" should be "PETSc".

2022-12-01 22:52 UTC, aostace01 commented on src/Examples/Flowsheets/temperature_swing_adsorption/TSA_CO2_example_1DFixedBed.ipynb
> +    "2) the NETL 32D property package."
Remove points at the end of numbered list elements (for consistency)?

2022-12-01 22:52 UTC, aostace01 commented on src/Examples/Flowsheets/temperature_swing_adsorption/TSA_CO2_example_1DFixedBed.ipynb
> +    "1) The flowsheet block of the simulation i.e. the adsorption flowsheet\n",
Comma missing around "i.e.".

2022-12-01 22:52 UTC, aostace01 commented on src/Examples/Flowsheets/temperature_swing_adsorption/TSA_CO2_example_1DFixedBed.ipynb
> +    "1) The flowsheet block of the simulation i.e. the adsorption flowsheet\n",
Comma missing around "i.e.".

2022-12-01 22:52 UTC, aostace01 commented on src/Examples/Flowsheets/temperature_swing_adsorption/TSA_CO2_example_1DFixedBed.ipynb
> +    "No object is returned by this function"
Period missing at the end of the sentence.

2022-12-01 22:52 UTC, aostace01 commented on src/Examples/Flowsheets/temperature_swing_adsorption/TSA_CO2_example_1DFixedBed.ipynb
> +    "- The petsc integrator is used for simulating the time trajectory. See https://idaes-pse.readthedocs.io/en/stable/reference_guides/core/solvers.html#petsc-utilities for more details.\n"
Here, too, I think "Petsc" and "petsc" should be "PETSc".

2022-12-01 22:52 UTC, aostace01 commented on src/Examples/Flowsheets/temperature_swing_adsorption/TSA_CO2_example_1DFixedBed.ipynb
> +    "#### Setup Petsc integrator and simulate desorption step"
Another "Petsc" :)

2022-12-02 14:51 UTC, bpaul4 commented
@aostace01 thank you for your review, I will look over and address your suggestions. Regarding the SVG model tags, I believe those may be determined on the `idaes-pse` flowsheet end when the tags are generated. I will investigate if I may directly edit the files in the `examples-pse` repository.

2022-12-08 15:17 UTC, jghouse88 commented
@bpaul4 Do you know why power_generation files are changing?

2022-12-08 15:54 UTC, bpaul4 commented
@jghouse88 While fixing the TSA notebook, I noticed other index issues and addressed those as well. I added the image files to the proper `docs/` folders as part of properly indexing the power generation examples, but no example or model files are changed in the `src/` directory.

2022-12-08 18:36 UTC, bpaul4 commented
In light of the transition to a new repository, I left the SVG files alone for now. We can address those in a PR to the new repository if we would like to update those later.

2022-12-22 14:44 UTC, aostace01 requested changes
Brandon, I changed the title of the PR from "Temperature swing adsorption example" to "1D fixed bed adsorption/desorption example" (to better convey that this example is an adsorption step followed by a desorption step, rather than a TSA cycle example). Can you please remove references to TSA from the TSA_CO2_example_1DFixedBed.ipynb, notebook_index.yml, and notebook_index.ipynb files, and where appropriate, rephrase along the lines of "adsorption/desorption example"? Other than this, everything else looks good to me. Thanks!

2022-12-23 14:07 UTC, andrewlee94 requested changes
Overall, most of my comments are asking for more detail and explanation. These are examples, so we need to explain to the user what is happening and why so that they can learn to do it themselves.

Comments on the notebook (as it is too large for me to comment on specific lines):

1. Need more introduction and a summary. What does this example show, what will be learnt, and why should the reader be interested?
1. Cycle details, remove the quotation marks around component names in the mole fraction specification.
2. Import custom libraries and functions - explain a bit more about what these are and why they need to be imported separately (and not from IDAES).
3. Function "fb_model_setup" - explain why we need to build this as a function. Also, make the heading title more explanatory, e.g. "Create a Function to Build the Flowsheet".
4. Function "fb_fix_conditions" - as above.
5. Setup solver for initialization - remove commented line on "tol", and explain why "bound_push" is required (and note the limitations of this too so users can understand).
6. Adsorption simulation - I feel there should always be some descriptive text in each markdown cell (and between all code cells, even if it is just one sentence). You need to explain what you are doing and why (users are generally reading these to learn).
7. Initialize model - we are going to want to update this example very soon to use the new initialization and scaling tools (once I get people to review and approve them). This will give an official interface to the block triangularization solve, and hopefully also remove the need for bound_push (due to variable scaling).
8. PETSc integrator - need to explain more about what is going on here and how this differs from the IPOPT solve. Also, can we cut back on the amount of output shown from PETSc?
9. Plots - need to explain the plots, and point out key features.

2023-01-05 13:37 UTC, andrewlee94 approved these changes

2023-01-05 15:08 UTC, aostace01 approved these changes
Looks good - thank you, Brandon.

2023-01-05 17:29 UTC, andrewlee94 commented
@lbianchi-lbl Could you take a look at why the notebooks are failing to convert on Window Python 3.7 please?

2023-01-12 19:26 UTC, merged