Adding Methanol Synthesis Flowsheet Example Notebook
IDAES/examples-pse pull request #98
Opened 2022-02-15 16:49 UTC by bpaul4

## Fixes # .

## Proposed changes:
- Adding methanol synthesis example notebook to EXAMPLES-PSE repository

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-03-25 19:58 UTC, lbianchi-lbl commented
@bpaul4 If you'd like to test this PR with IDAES/idaes-pse#711 before that one is merged into `idaes-pse:main`, you should be able to just set the proper value here: https://github.com/IDAES/examples-pse/blob/79dfed7ade2a352bf9d847bbd155ed40bf6d4559/.github/workflows/main.yml#L17, i.e.:

```yaml
env:
  IDAES_CONDA_ENV_NAME_DEV: examples-pse-dev
  IDAES_PSE_REQUIREMENT: idaes-pse[prerelease] @ git+https://github.com/IDAES/idaes-pse@refs/pull/711/head
``

2022-05-19 16:04 UTC, andrewlee94 requested changes
As a general comment, I think there needs to be more guidance to the user if this is to be a proper example. Each step should explain what is happening, why and what the expected outcome is.

2022-05-19 16:04 UTC, andrewlee94 commented on src/Examples/Flowsheets/methanol_synthesis.ipynb
> +   "cell_type": "code",
It is hard to tell via the GitHub interface, but this appears to be missing the tags to indicate that this is a testing cell and should not be included in the public facing version,

2022-08-04 18:34 UTC, ksbeattie commented
@andrewlee94, @MAZamarripa this is ready for re-review.

2022-08-04 18:39 UTC, andrewlee94 approved these changes
I took a quick look and only had a couple of minor observations:

1. A summary upfront to explain the purpose of the example (in a sentence or two) would probably be valuable. This would help inform users of whether this example is of interest to them.

2. Do we really need 500 iterations for IPOPT? Unless there is a good reason, I think we should be using a more reasonable value for this. Otherwise, readers will start to think 500 iterations is expected/acceptable, when really it should solve in less than 100 in most cases.

2022-08-08 14:31 UTC, bpaul4 commented
@MAZamarripa this is ready for your review when you have a moment. Thank you!

2022-08-11 19:15 UTC, MAZamarripa approved these changes
lgtm

2022-08-11 21:10 UTC, merged